// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaz6R-fqMhsSytluHgncdaSUDytgflLQM',
    appId: '1:370312580610:web:5598ef19739aa7f170a11b',
    messagingSenderId: '370312580610',
    projectId: 'wolfteam-f01f4',
    authDomain: 'wolfteam-f01f4.firebaseapp.com',
    databaseURL: 'https://wolfteam-f01f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wolfteam-f01f4.appspot.com',
    measurementId: 'G-R18V8CK55E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZabMViZon9AD0TAHJ6Ev8ES-bXlEhCBs',
    appId: '1:370312580610:android:85f2148d8166924670a11b',
    messagingSenderId: '370312580610',
    projectId: 'wolfteam-f01f4',
    databaseURL: 'https://wolfteam-f01f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wolfteam-f01f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcE2mqpNod60gFDwT8yvxgty5mn48KrKI',
    appId: '1:370312580610:ios:83ddadb882c17c7f70a11b',
    messagingSenderId: '370312580610',
    projectId: 'wolfteam-f01f4',
    databaseURL: 'https://wolfteam-f01f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wolfteam-f01f4.appspot.com',
    iosClientId: '370312580610-pm1iq31bk0up8ot8chrhonhj5b4fa9e4.apps.googleusercontent.com',
    iosBundleId: 'com.wolvesvn.wolvesvn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcE2mqpNod60gFDwT8yvxgty5mn48KrKI',
    appId: '1:370312580610:ios:5c7025eeb84c9fe070a11b',
    messagingSenderId: '370312580610',
    projectId: 'wolfteam-f01f4',
    databaseURL: 'https://wolfteam-f01f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wolfteam-f01f4.appspot.com',
    iosClientId: '370312580610-qbtt7n1brrv58triuvh1lic6t9dl858f.apps.googleusercontent.com',
    iosBundleId: 'com.wolvesvn.wolvesvn.RunnerTests',
  );
}
